### ISSUE TITLE
Crash on the most recent 1.14.2 version when booting game.

### ISSUE THREAD

**Issue by Gbergz** [Markus23/mycommands#1]
Title^

Crash-report: [https://paste.ee/p/ddN3d](https://paste.ee/p/ddN3d)

Mod-version: Mycommands-1.14.2-02
Fabric API version: fabric-api-0.3.0+build.175

**Comment by Markus23** [comment]
Quickfix  command gm temporary disabled

**Comment by ghost** [comment]
On the -03 version I am getting it with the Tpa command.


---- Minecraft Crash Report ----
// My bad.

Time: 5/31/19 9:36 AM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors!
	at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.method_1503(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	Suppressed: java.lang.IllegalAccessError: no such method: de.mybukit.mycommands.commands.CommandTpa.register(CommandDispatcher)void/invokeStatic
		at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:483)
		at de.mybukit.mycommands.MyCommands.onInitialize(MyCommands.java:88)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointClient$$Lambda$1400/901737914.accept(Unknown Source)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.lambda$logErrors$0(EntrypointUtils.java:38)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils$$Lambda$1401/1000347057.accept(Unknown Source)
		at java.util.ArrayList.forEach(ArrayList.java:1249)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:36)
		... 11 more
	Caused by: java.lang.NoClassDefFoundError: net/minecraft/network/chat/Component
		at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
		at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:962)
		at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:987)
		at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1390)
		at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1746)
		at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477)
		... 17 more
	Caused by: java.lang.ClassNotFoundException: net.minecraft.network.chat.Component
		at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
		at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:160)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		... 23 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.method_1503(class_310.java)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.14.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3384665312 bytes (3227 MB) / 3657433088 bytes (3488 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		alwaysdroploot: Always Drop Loot 3.5.0+mc1.14.1
		anvil_fix: AnvilFix 1.1.2
		autoconfig1: Auto Config v1 1.1.2+mc1.14.1
		beachslimes: Beach Slimes 1.2.0+mc1.14.1
		blue_endless_jankson: jankson 1.1.2
		cloth: Cloth Events 0.3.1+build.23
		cloth-config: Cloth Config 0.2.4+build.17
		cursedchests: CursedChests 2.2.17
		dataloader: Data Loader 1.0.0+mc1.14.1
		easyexcavate: Easy Excavate 1.5.1
		everythingisahat: Everything is a Hat 1.0.1
		fabric: Fabric API 0.3.0+build.175
		fabric-api-base: fabric-api-base 0.1.0+59147463
		fabric-commands-v0: fabric-commands-v0 0.1.1+25fd0c52
		fabric-containers-v0: fabric-containers-v0 0.1.2+25fd0c52
		fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+45e1a1c8
		fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.0+59147463
		fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.0+59147463
		fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.0+59147463
		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+59147463
		fabric-keybindings-v0: fabric-keybindings-v0 0.1.0+59147463
		fabric-language-kotlin: Fabric Language Kotlin 1.3.30+build.2
		fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+59147463
		fabric-models-v0: fabric-models-v0 0.1.0+59147463
		fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.1+25fd0c52
		fabric-networking-v0: fabric-networking-v0 0.1.2+200eb5c2
		fabric-object-builders-v0: fabric-object-builders-v0 0.1.1+9fe2f882
		fabric-registry-sync-v0: fabric-registry-sync-v0 0.2.1+4d26f9ba
		fabric-renderer-api-v1: fabric-renderer-api-v1 0.1.0+02a46d5b
		fabric-renderer-indigo: fabric-renderer-indigo 0.1.4+620b4d61
		fabric-rendering-data-attachment-v1: fabric-rendering-data-attachment-v1 0.1.0+02a46d5b
		fabric-rendering-fluids-v1: fabric-rendering-fluids-v1 0.1.0+dc4c57c2
		fabric-rendering-v0: fabric-rendering-v0 0.1.0+59147463
		fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.1+59147463
		fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.0+59147463
		fabric-textures-v0: fabric-textures-v0 0.1.4+792c1c35
		fabricloader: Fabric Loader 0.4.8+build.154
		faeriefire: Faerie Fire 1.0.0
		flameretardant: Flame Retardant 1.0.0
		infinityfix: Infinity Fix 1.0.4
		leaf-decay: Leaf Decay 1.0.3
		leveluphp: Level Up HP 4.3.0+mc1.14.2
		libblockattributes: LibBlockAttributes 0.4.2
		mbackpacks: Backpacks MOD 1.1.0
		modmenu: Mod Menu 1.5.4-85
		mycommands: MyCommands Fabric 1.14.2-03
		netherthings: Nether Things 1.1.2
		overheadhp: Over Head HP 0.1.2
		railboost: railboost 0.2.0
		roughlyenoughitems: Roughly Enough Items 2.9.1+build.121
		smoothbedrock: Smooth Bedrock (Fabric) 1.1.3
		stockpile: Stockpile 1.0.6+1.14.1
		torcherino: Torcherino 1.7.48
		vanilla-toolsets: Vanilla Toolsets 1.1.2
		voxelmap: VoxelMap 1.9.3
	Launched Version: fabric-loader-0.4.8+build.154-1.14.2+build.2
	LWJGL: 3.2.1 build 12
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: ~~ERROR~~ NullPointerException: null
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>

**Comment by ghost** [comment]
I also get this in the log, if this helps.

[09:36:05] [main/WARN]: Error loading class: net/minecraft/entity/LivingEntity (java.lang.ClassNotFoundException: net/minecraft/entity/LivingEntity)
[09:36:05] [main/WARN]: @Mixin target net.minecraft.entity.LivingEntity was not found mycommands.common.json:MixinDeathBack

**Comment by XuyuEre** [comment]
yes,me too.

**Comment by SDUBZ** [comment]
did you guys try with fabric api release version not alpha or beta versions ?

**Comment by SDUBZ** [comment]
[crash-2019-06-01_14.42.59-client.txt](https://github.com/Markus23/mycommands/files/3243404/crash-2019-06-01_14.42.59-client.txt)
even with fabric api 3.0 157 release it still crashes 

using myc: Mycommands-1.14.2-03

**Comment by XuyuEre** [comment]
I use `[1.14.2] Fabric API 0.3.0 build 175` ，it still crashes .It is the laster one of fabric that i can download and use.

**Comment by ghost** [comment]
Seems to have something to do with net.minecraft.network.chat.Component. It seems to be not finding that class for some reason.
