### ISSUE TITLE
spawn doesnt work between dimensions, /homes dont work in any dimension

### ISSUE THREAD

**Issue by wh0oo** [Markus23/mycommands#15]
/spawn does not work between dimensions, even after using /setspawn or /setworldspawn
/sethome and then /home do not work at all.  (i think that is a file write error because I see a what looks like a file write error in java scroll past.  

`[23:37:46] [Server thread/INFO]: [STDERR]: java.io.IOException: No such file or directory
[23:37:46] [Server thread/INFO]: [STDERR]:      at java.io.UnixFileSystem.createFileExclusively(Native Method)
[23:37:46] [Server thread/INFO]: [STDERR]:      at java.io.File.createNewFile(File.java:1012)
[23:37:46] [Server thread/INFO]: [STDERR]:      at de.mybukit.mycommands.helper.PlayerData.save(PlayerData.java:106)
[23:37:46] [Server thread/INFO]: [STDERR]:      at de.mybukit.mycommands.helper.PlayerData.load(PlayerData.java:118)
[23:37:46] [Server thread/INFO]: [STDERR]:      at de.mybukit.mycommands.helper.PlayerData.init(PlayerData.java:81)
[23:37:46] [Server thread/INFO]: [STDERR]:      at de.mybukit.mycommands.helper.PlayerData.<init>(PlayerData.java:39)
[23:37:46] [Server thread/INFO]: [STDERR]:      at de.mybukit.mycommands.commands.CommandHome.execut(CommandHome.java:62)
`

The homes.txt that is to be expected is present.
This is a Linux box, if that matters, so I want to add that the user running all the procs has the proper permissions to create/write to all the files as needed.

Thank you!

**Comment by wh0oo** [comment]
i deleted the homes.txt and restarted the server instance.  the file was recreated.  I cannot explain why but /home and all the related commands now work.  And that file still isnt being written to.  

--

On further review, I see now that the homes are written to a json file.  

/spawn is still broken across dimensions though.

**Comment by Markus23** [comment]
Warp Home Spawn fixed for the second.
