### ISSUE TITLE
/spawn crash

### ISSUE THREAD

**Issue by RichardIsSoarx** [Markus23/mycommands#6]
When issuing the /spawn command the server crashes. I am using the latest 1.14.2 Fabric version.

**Comment by RichardIsSoarx** [comment]
[22:24:41] [Server thread/WARN]: handleDisconnection() called twice
[22:24:41] [Server thread/INFO]: waffleworrior[/127.0.0.1:61039] logged in with entity id 4937 at (-693.9459485731923, 68.0, 746.3686681445415)
[22:24:42] [Server thread/INFO]: waffleworrior joined the game
[22:31:29] [Server thread/INFO]: waffleworrior was slain by Spider
[22:47:32] [Server thread/INFO]: waffleworrior fell from a high place
[22:49:15] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: net.minecraft.class_3218.method_8395()Lnet/minecraft/class_2338;
	at de.mybukit.mycommands.commands.CommandSpawn.execute(CommandSpawn.java:33) ~[Mycommands-1.14.2-05.jar:?]
	at de.mybukit.mycommands.commands.CommandSpawn.lambda$register$1(CommandSpawn.java:23) ~[Mycommands-1.14.2-05.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[intermediary-server.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176) ~[intermediary-server.jar:?]
	at net.minecraft.class_2170.method_9249(class_2170.java:223) ~[intermediary-server.jar:?]
	at net.minecraft.class_3244.method_14370(class_3244.java:1096) ~[intermediary-server.jar:?]
	at net.minecraft.class_3244.method_12048(class_3244.java:1083) ~[intermediary-server.jar:?]
	at net.minecraft.class_2797.method_12115(class_2797.java:37) ~[intermediary-server.jar:?]
	at net.minecraft.class_2797.method_11054(class_2797.java:9) ~[intermediary-server.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:15) ~[intermediary-server.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:135) ~[intermediary-server.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:114) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:702) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:696) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:123) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:681) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.handler$modifiedRunLoop$zbb000(MinecraftServer.java:2268) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:611) [intermediary-server.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
[22:49:15] [Server thread/ERROR]: This crash report has been saved to: C:\Users\bryar\Desktop\test1065\.\crash-reports\crash-2019-06-02_22.49.15-server.txt
[22:49:15] [Server thread/INFO]: Stopping server
[22:49:15] [Server thread/INFO]: Saving players
[22:49:15] [Server thread/INFO]: Saving worlds
[22:49:15] [Server thread/INFO]: Saving chunks for level 'world'/minecraft:the_end
[22:49:16] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[22:49:16] [Server thread/INFO]: Saving chunks for level 'world'/minecraft:overworld
[22:49:16] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[22:49:16] [Server thread/INFO]: Saving chunks for level 'world'/minecraft:the_nether
[22:49:16] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[22:49:16] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[22:49:16] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[22:49:16] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved

**Comment by RichardIsSoarx** [comment]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 6/2/19 8:07 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.class_3218.method_8395()Lnet/minecraft/class_2338;
	at de.mybukit.mycommands.commands.CommandSpawn.execute(CommandSpawn.java:33)
	at de.mybukit.mycommands.commands.CommandSpawn.lambda$register$1(CommandSpawn.java:23)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176)
	at net.minecraft.class_2170.method_9249(class_2170.java:223)
	at net.minecraft.class_3244.method_14370(class_3244.java:1096)
	at net.minecraft.class_3244.method_12048(class_3244.java:1083)
	at net.minecraft.class_2797.method_12115(class_2797.java:37)
	at net.minecraft.class_2797.method_11054(class_2797.java:9)
	at net.minecraft.class_2600.method_11072(class_2600.java:15)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:135)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:114)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:702)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:696)
	at net.minecraft.class_1255.method_5383(class_1255.java:99)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:680)
	at net.minecraft.server.MinecraftServer.handler$modifiedRunLoop$zbb000(MinecraftServer.java:2268)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:611)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 554851712 bytes (529 MB) / 1041235968 bytes (993 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 0 total; 
	Fabric Mods: 
		fabric: Fabric API 0.3.0+build.175
		fabric-api-base: fabric-api-base 0.1.0+59147463
		fabric-commands-v0: fabric-commands-v0 0.1.1+25fd0c52
		fabric-containers-v0: fabric-containers-v0 0.1.2+25fd0c52
		fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+45e1a1c8
		fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.0+59147463
		fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.0+59147463
		fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.0+59147463
		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+59147463
		fabric-keybindings-v0: fabric-keybindings-v0 0.1.0+59147463
		fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+59147463
		fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.1+25fd0c52
		fabric-networking-v0: fabric-networking-v0 0.1.2+200eb5c2
		fabric-object-builders-v0: fabric-object-builders-v0 0.1.1+9fe2f882
		fabric-registry-sync-v0: fabric-registry-sync-v0 0.2.1+4d26f9ba
		fabric-renderer-api-v1: fabric-renderer-api-v1 0.1.0+02a46d5b
		fabric-renderer-indigo: fabric-renderer-indigo 0.1.4+620b4d61
		fabric-rendering-data-attachment-v1: fabric-rendering-data-attachment-v1 0.1.0+02a46d5b
		fabric-rendering-fluids-v1: fabric-rendering-fluids-v1 0.1.0+dc4c57c2
		fabric-rendering-v0: fabric-rendering-v0 0.1.0+59147463
		fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.1+59147463
		fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.0+59147463
		fabricloader: Fabric Loader 0.4.8+build.154
		mycommands: MyCommands Fabric 1.14.2-05
		quickcarpet: QuickCarpet 1.12.0
	Player Count: 1 / 20; [class_3222['RichardIsSoarx'/29, l='world', x=-640.52, y=66.88, z=799.42]]
	Data Packs: fabric/quickcarpet, fabric/fabric-mining-levels-v0, vanilla, file/Essentials_Datapack (incompatible)
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by Markus23** [comment]
fix compile error /spawn /heal
